import { Ubuntu } from "next/font/google";
import Header from "@/components/header";
import "../styles/index/index.scss";

const ubuntu = Ubuntu({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="nl">
      <body className={ubuntu.className}>
        {children}
        <Header/>
      </body>
    </html>
  );
}
