import { Ubuntu } from "next/font/google";
import Head from 'next/head';
import Header from "@/components/header";

const ubuntu = Ubuntu({
    weight: ['400', '500', '700'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "../styles/index/index.css";

export default function RootLayout({ children }) {
  return (
    <html lang="nl">
        <Head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>{metadata.title}</title>
        </Head>
        <body className={ubuntu.className}>
            {children}
            <Header/>
        
        </body>
    </html>
  );
}
