import { Poppins } from "next/font/google";
import Head from 'next/head';

const poppins = Poppins({
    weight: ['400', '600', '700'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import "../styles/index.css";

export default function RootLayout({ children }) {
  return (
    <html lang="nl">
        <Head>
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <title>{metadata.title}</title>
        </Head>
      <body className={poppins.className}>
        {children}
      </body>
    </html>
  );
}
